# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js 20
      uses: actions/setup-node@v3
      with:
        registry-url: 'https://registry.npmjs.org/'
        node-version: 20
        cache: 'npm'
        
    - name: Configure Git
      run: |
        git config --global user.email "${{ secrets.GIT_USER_EMAIL }}"
        git config --global user.name "${{ secrets.GIT_USER_NAME }}"
    - name: Install dependencies, build & release
      env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      run: |
        npm ci
        npm run build --if-present
        bash ./release.sh
